version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.8"

formats: [pdf]
sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [doc]
